### ISSUE TITLE
Updated to 0.19.0 and issues starting Node-Red

### ISSUE THREAD

**Issue by alexinthis** [Dirnei/node-red-contrib-zigbee2mqtt-devices#93]
Hi, after updating the

Here is what Node-Red is showing:

 Feb 22:50:14 - [info] Started flows

1 Feb 22:50:14 - [info] [zigbee2mqtt-server:zigbee2mqtt Server] MQTT Connected

1 Feb 22:50:14 - [info] [zigbee2mqtt-server:zigbee2mqtt Server] Refreshing devices

1 Feb 22:50:14 - [info] [mqtt-broker:MQTT Server] Connected to broker: mqtt://10.0.0.2:1883

1 Feb 22:50:14 - [red] Uncaught Exception:

1 Feb 22:50:14 - TypeError: Cannot read property 'split' of undefined

    at MqttSubscription.callback (/data/node_modules/node-red-contrib-zigbee2mqtt-devices/dist/nodes/hue-dimmer/devices-hue.js:13:49)

    at MqttSubscription.invokeIfMatch (/data/node_modules/node-red-contrib-zigbee2mqtt-devices/dist/lib/mqtt.js:28:18)

    at subscriptions.(anonymous function).forEach.sub (/data/node_modules/node-red-contrib-zigbee2mqtt-devices/dist/zigbee2mqtt-config.js:33:25)

    at Array.forEach (<anonymous>)

    at BridgeConfigConstructor.broker.subscribe (/data/node_modules/node-red-contrib-zigbee2mqtt-devices/dist/zigbee2mqtt-config.js:32:36)

    at MqttClient.handler (/usr/src/node-red/node_modules/@node-red/nodes/core/network/10-mqtt.js:320:25)

    at MqttClient.emit (events.js:198:13)

    at MqttClient._handlePublish (/usr/src/node-red/node_modules/mqtt/lib/client.js:1277:12)

    at MqttClient._handlePacket (/usr/src/node-red/node_modules/mqtt/lib/client.js:410:12)

    at work (/usr/src/node-red/node_modules/mqtt/lib/client.js:321:12)

    at process._tickCallback (internal/process/next_tick.js:61:11)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! node-red-docker@1.2.7 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`

npm ERR! Exit status 1



 

npm ERR! Failed at the node-red-docker@1.2.7 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /data/.npm/_logs/2021-02-01T11_50_14_083Z-debug.log

> node-red-docker@1.2.7 start /usr/src/node-red

> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"

1 Feb 22:50:16 - [info] 

------------

It seems to happen just as I fix up the username and password to the MQTT Broker. 

Did anyone else have issues after upgrading? 

Thanks,
Alex

**Comment by Dirnei** [comment]
I will have a look and let you know when I know more
